# Generated by Django 3.1.4 on 2021-01-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('unique_ID', models.CharField(help_text="Enter the patient's unique ID: ", max_length=20, primary_key=True, serialize=False, unique=True)),
                ('first_Name', models.CharField(help_text="Enter the patient's first name: ", max_length=20)),
                ('last_Name', models.CharField(help_text="Enter the patient's last name: ", max_length=20)),
                ('date_of_birth', models.DateField(help_text="Enter the patient's date of birth: ")),
                ('address', models.CharField(default='null', help_text='Enter address of residence', max_length=40)),
                ('phone', models.CharField(default=0, help_text="Enter the patient's phone number", max_length=12)),
                ('email', models.EmailField(default='null', help_text="Enter the patient's email address: ", max_length=40)),
                ('reason_for_visit', models.TextField(default='null', help_text='Enter the reason for visit', max_length=300)),
            ],
            options={
                'ordering': ['unique_ID', 'first_Name', 'last_Name', 'date_of_birth', 'address', 'phone', 'email', 'reason_for_visit'],
            },
        ),
    ]
