# Generated by Django 3.1.4 on 2021-01-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commoninfo', '0002_auto_20210115_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank='True', help_text="Enter the patient's email address: ", max_length=40),
        ),
    ]
