# Generated by Django 3.1.4 on 2021-01-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commoninfo', '0004_auto_20210115_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(help_text='Enter address of residence', max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(help_text="Enter the patient's phone number", max_length=12),
        ),
        migrations.AlterField(
            model_name='patient',
            name='reason_for_visit',
            field=models.TextField(help_text='Enter the reason for visit', max_length=300),
        ),
    ]
