# Generated by Django 3.1.4 on 2021-01-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commoninfo', '0005_auto_20210118_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='first_Name',
            field=models.CharField(help_text="Enter the patient's first name: ", max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_Name',
            field=models.CharField(help_text="Enter the patient's last name: ", max_length=20),
        ),
    ]
