# Generated by Django 3.1.4 on 2021-01-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commoninfo', '0010_auto_20210119_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(default='null', help_text='Enter your city of residence', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(default='null', help_text='Enter your state of residence.', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='zip_code',
            field=models.PositiveIntegerField(default=1, help_text='Enter your zipcode'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(help_text='Enter your street address', max_length=40),
        ),
    ]
